GET http://localhost:3001/players

###
PUT http://localhost:3001/players/5
Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 16,
  "role": "Bowler"
}
###
GET http://localhost:3001/players/1
